Admin now can: see companies, accept companies and reject companies
TreinaDev/pagamentos-alpha pull request #53
Opened 2021-11-24 04:36 UTC by caiosant

2021-11-25 17:54 UTC, joaorsalmeida submitted a review, later dismissed
Ficou bacana!

2021-11-25 17:54 UTC, joaorsalmeida commented on spec/models/rejected_company_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Se der, apague essa linha antes do merge

2021-11-25 17:54 UTC, joaorsalmeida commented on spec/factories/rejected_companies.rb
> +    reason { 'MyText' }
Bora colocar um texto 'dummy' aqui? Um Lorem Ipsum da vida talvez?!

2021-11-25 17:56 UTC, joaorsalmeida requested changes

2021-11-25 17:56 UTC, joaorsalmeida commented on spec/system/admin/admin_see_companies_spec.rb
> +    click_on 'Empresas Pendentes'
De onde vem as empresas pendentes nesse teste? Da 'factory' de usuarios? Se for isso ficou ruim a legibilidade. Prefiro que as empresas sejam criadas diretamente no teste e explicitamente com status pendente.

2021-11-25 18:37 UTC, caiosant commented on spec/models/rejected_company_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Acabou passando! Acertado já!

2021-11-25 18:47 UTC, caiosant commented on spec/factories/rejected_companies.rb
> +    reason { 'MyText' }
Texto adicionado, conversando com o time escolhemos colocar um da internet do que adicionar a gem apenas para isto.

2021-11-29 20:27 UTC, alleSilva approved these changes
Conferido

2021-11-29 20:29 UTC, joaorsalmeida approved these changes

2021-11-29 20:30 UTC, merged